config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :relationships, only: [:create, :destroy]
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers, :follow, :follower
    end
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    # ↑resourceが複数形になっていてidを上手く渡せないroute matchエラーが起きていた
  end
  
  root 'home#top'
  get 'home/about', to: 'home#about'
  get 'users/:id/following', to: 'users#following'
  get 'users/:id/followers', to: 'users#followers'
  get '/search' => 'search#search'
  post '/books/:book_id/favorites' => "favorites#create"
  delete '/books/:book_id/favorites' => "favorites#destroy"
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  # bookと紐付いているからと言って、userと紐づいているわけではない！

  validates :body, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    # @book = Book.find(params[:book_id])
    # @book.book_comments.user_id = current_user
    # @book.book_comments.create(book_comment_params)
    # # binding.pry
    # redirect_to book_path(@book)

    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.find(params[:id])
    @comment.destroy
    render :index
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:body, :book_id, :user_id)
    end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
コメント数：<%= comments.count %>
<%#= rand(10) %>

app/views/book_comments/_form.html.erb
<%= form_with(model: [book, comment], url: book_book_comments_path(@book) ) do |f| %>
  <div>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>
  <div>
    <%= f.submit "送信", class: "col-xs-12 btn btn-primary"  %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <ul class="ul-comment">
      <li class="li-comment">
        <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image", size: "40x40" %>
      </li>
      <li class="li-comment"><%= comment.body %></li>
      <% if comment.user == current_user %>
        <li class="li-comment">
          <%= link_to "Destroy", book_book_comment_path(comment.book_id, comment.id), method: :delete, remote: true, class: "btn btn-danger destroy_book_#{@book.id}" %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <hr>
<% end %>

app/views/book_comments/count.js.erb
$("#count").html("<%= j(render 'index', { comments: @comment.book.book_comments }) %>")

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.book.book_comments }) %>")
$("textarea").val('')

$("#count").html("<%= j(render 'count', { comments: @comment.book.book_comments }) %>")